const ticketsData = [
  {
    id: "#1001",
    title: "Login Issues - Can't Access Account",
    description:
      "Customer is unable to log in to their account. They tried resetting the password multiple times but still can’t access their dashboard.",
    customer: "Jacob Smith",
    priority: "High",
    status: "Open",
    createdAt: "2025-05-26",
  },
  {
    id: "#1002",
    title: "Payment Failed - Card Declined",
    description:
      "Customer attempted to pay using Visa ending 1234 but the payment keeps failing despite sufficient balance.",
    customer: "John Brown",
    priority: "High",
    status: "Open",
    createdAt: "2025-06-10",
  },
  {
    id: "#1003",
    title: "Unable to Download Invoice",
    description: "Customer cannot download their January invoice from the billing section.",
    customer: "Michele Davis",
    priority: "Medium",
    status: "In-Progress",
    createdAt: "2025-07-21",
  },
  {
    id:"#1004",
    title: "Subscription Auto-renewal",
    description: "Customer wants to enable auto-renewal for their subscription but the toggle is disable.",
    customer: "Emma Stone",
    priority: "High",
    status: "In Progress",
    createdAt: "2025-09-22",
  },
  {
   id:"#1005",
    title: "Two Factor-Authentication Issue",
    description: "Customer is not receiving 2FA code on their registering phone number.",
    customer: "Alex Smith",
    priority: "Medium",
    status: "Open",
    createdAt: "2025-09-21",
  },
  {
    id:"#1006",
    title: "Payment failed-Card Declined",
    description: "Customers attempted to pay using visa ending 1234 but the payments keep failing despite sufficient balance",
    customer: "Sophia Kim",
    priority: "High",
    status: "In Progress",
    createdAt: "2025-09-19",
  },
  {
    id:"#1007",
    title: "Refund Not Processed",
    description: "Customer requested a refund two weeks ago but has not received the amount yet.",
    customer: "Michael Clark",
    priority: "Low",
    status: "Resolved",
    createdAt: "2025-09-17",
  },
  {
    id:"#1008",
    title: "Incorrect Billing Address",
    description: "Customers billing address shows a different city. They updated it but it still displays the old one.",
    customer: "Olivia Brown",
    priority: "Low", 
    status: "Open",
    createdAt: "2025-09-16",
  },
  {
    id:"#1009",
    title: "Unable to update Profile Picture",
    description: " Customer tries to upload a new profile picture but gets upload failed error.",
    customer: "Chris Green",
    priority: "High",
    status: "In Progress",
    createdAt: "2025-09-23",
  },
  {
    id:"#1010",
    title: "Missing order confirmation Email",
    description: "Customer placed an order but did not receive a confirmation email even though the payment succeeded .",
    customer: "Liam Johnson",
    priority: "Medium",
    status: "Open",
    createdAt: "2025-09-24",
  },
];

export default ticketsData;
